"""add transaction table

Revision ID: 0002
Revises: 0001
Create Date: 2024-11-30 23:06:51.668084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('device_id', sa.Float(), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('tran_code', sa.Integer(), nullable=False),
    sa.Column('mcc', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('card_type', sa.String(length=50), nullable=False),
    sa.Column('pin_inc_count', sa.Integer(), nullable=False),
    sa.Column('card_status', sa.String(length=100), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('sum', sa.Float(), nullable=False),
    sa.Column('oper_type', sa.String(length=50), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('pred', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
